### ISSUE TITLE
[Feature Request] Media que

### ISSUE THREAD

**Issue by meliksu** [Fenny/ChromecastJS#2]
How can I change the media? if I connected to chromecast and a video is played... how can I play the next video? For example when I have a playlist.

**Comment by Fenny** [comment]
Hi,

Did you try to send the next video to the object?

```
cc.cast({ content: 'video.mp4' })
```javascript

**Comment by meliksu** [comment]
Yes, it just re-opens the chromecast popup. Do you have any idea?

**Comment by meliksu** [comment]
Thanks in advance, hope you find a solution :)

**Comment by Fenny** [comment]
Hey Meliksu,

I couldn't find a solution, it seems to be a problem among other developers.
Maybe these answers could help us: 

https://stackoverflow.com/questions/33653566/pushing-a-playlist-to-chromecast-using-castcompanionlibrary

Had no time to look into the MediaQueueItem method.
