### ISSUE TITLE
Update the data?

### ISSUE THREAD

**Issue by Ilario42** [Fenny/ChromecastJS#4]
Hello Friend!
Great project, the only one that worked!
I modified the code according to my needs (I hope this is not a problem). I need to update about every 20 seconds in the var "Media" "content" "poster" "title" "description".

How can I do? Can you give me a hand?

Thank you, give your answer! Happy Easter!

**Comment by Fenny** [comment]
Hi,

Did you try to change the global variables as shown in the description?

cc.Media.poster
cc.Media.title
cc.Media.description

**Comment by Ilario42** [comment]
@Fenny  Yes, cc.Media was changed but chromecast not refresh the info.

**Comment by Fenny** [comment]
I will look into it this week. If it's possible I will update the code.

**Comment by Ilario42** [comment]
> I will look into it this week. If it's possible I will update the code.

@Fenny i wait your update

**Comment by Fenny** [comment]
@Ilario42 
I didn't mange to figure out how to update those variables while casting, I'm closing it for now until someone knows how to fix it.
