### ISSUE TITLE
Problem with subtitles

### ISSUE THREAD

**Issue by DubSeven** [Fenny/ChromecastJS#7]
Hello Fenny,

Thank you for this library.
I have a problem with subtitles.
The subtitle from your url works very well (https://fenny.github.io/ChromecastJS/demo/english.vtt)

But, when i replace it with my domaine, it's doesn't work anymore (https://blue-ia.com/UptoboxToChromecast/subtitles/files/65750f5ec0a89e3.vtt).

Do you have any idea ?

Thanks

**Comment by Fenny** [comment]
@DubSeven 
Make sure that your server supports CORS
