### ISSUE TITLE
Cast with authentication xampp apache

### ISSUE THREAD

**Issue by gustavog4** [Fenny/ChromecastJS#8]
Ok so im using authentication htpasswd (https://imalabya.wordpress.com/2014/09/21/set-a-authentication-password-in-xampp-using-htpasswd/)

But after adding it dont cast anymore

    cc.cast({
        content:     'http://example.com/video/hola.mp4'

**Comment by Fenny** [comment]
@gustavog4 
I don't think you can send custom http headers from the chromecast ( sender )
You could try to listen for the useragent "CrKey" and bypass the authentication.
